### ISSUE TITLE
song.js:24         .then(([lyric, song]) => song);

### ISSUE THREAD

**Issue by acomito** [StephenGrider/Lyrical-GraphQL#1]
```
[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
/Users/me/Desktop/websites/lyrical/server/models/song.js:24
        .then(([lyric, song]) => song);
               ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/arcomito/Desktop/websites-dev/lyrical/server/models/index.js:1:63)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
[nodemon] app crashed - waiting for file changes before starting...
```

I'm getting the above error on startup

**Comment by acomito** [comment]
If I delete that array parameter the next error I get is:


```
const { GraphQLObjectType, GraphQLList, GraphQLID, GraphQLNonNull } = graphql;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/arcomito/Desktop/websites-dev/lyrical/server/schema/schema.js:5:23)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/arcomito/Desktop/websites-dev/lyrical/server/server.js:6:16)
    at Module._compile (module.js:398:26)
[nodemon] app crashed - waiting for file changes before starting...
```

is this maybe a webpack/babel problem where I'm missing es6?

**Comment by acomito** [comment]
wrong node version!
